version: '3.3'

services:
  flask:
    build: ./flask
    expose:
      - "5002"
    container_name: flask2020
    command: gunicorn -b 0.0.0.0:5002 app:app --reload
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    container_name: nginx-flask